// Generated by CoffeeScript 1.6.3
var data, _i, _j, _results, _results1;

data = {
  title: 'a title',
  list: ['line a', 'line b', 'line c', 'line d'],
  map: {
    a: 'this is a',
    b: 'this is b',
    c: 'this is c'
  }
};

console.time('Handlebars');

(function() {
  _results = [];
  for (_i = 1; _i <= 10000; _i++){ _results.push(_i); }
  return _results;
}).apply(this).map(function() {
  return Handlebars.templates['template.hbs'](data);
});

console.timeEnd('Handlebars');

console.time('jade');

(function() {
  _results1 = [];
  for (_j = 1; _j <= 10000; _j++){ _results1.push(_j); }
  return _results1;
}).apply(this).map(function() {
  return jade.attrs(data);
});

console.timeEnd('jade');
